# Generated by Django 5.0.3 on 2024-03-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentaffairs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damages',
            old_name='Student',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='disciplinary',
            old_name='Student',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='games',
            old_name='Student',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='hostel',
            old_name='Student',
            new_name='student',
        ),
    ]
