# Generated by Django 5.0.3 on 2024-03-19 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentaffairs', '0002_rename_student_damages_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='Student',
            new_name='student',
        ),
    ]
